classDiagram
    class Animal {
        +String species
        +String habitat
        +eat()
        +sleep()
    }
    class Mammal {
        +String furColor
    }
    class Bird {
        +String featherColor
    }
    Animal <|-- Mammal
    Animal <|-- Bird

    class Auto {
        +String featherColor
    }

    Animal <|-- Auto


